CREATE TABLE drivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_drivers PRIMARY KEY (id),
    CONSTRAINT uk_drivers_document UNIQUE (document)
);

CREATE TABLE tourists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    birth_date DATE NOT NULL,
    document VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tourists PRIMARY KEY (id),
    CONSTRAINT uk_tourists_document UNIQUE (document)
);

CREATE TABLE trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    child_price NUMERIC(38,2) NOT NULL,
    end_date DATE NOT NULL,
    tourist_price NUMERIC(38,2) NOT NULL,
    tourists_limit INTEGER NOT NULL,
    start_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING','CONFIRMED','ONGOING','COMPLETED','CANCELLED')),
    trip_title VARCHAR(150) NOT NULL,
    CONSTRAINT pk_trips PRIMARY KEY (id)
);

CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    capacity INTEGER NOT NULL CHECK (capacity >= 1),
    license_plate VARCHAR(255) NOT NULL,
    vehicle_model VARCHAR(255) NOT NULL,
    vehicle_type VARCHAR(255) NOT NULL CHECK (vehicle_type IN ('SUV','BUS','VAN')),
    year INTEGER NOT NULL CHECK (year >= 1886),
    CONSTRAINT pk_vehicles PRIMARY KEY (id),
    CONSTRAINT uk_vehicles_license_plate UNIQUE (license_plate)
);

CREATE TABLE trip_tourists (
    trip_id BIGINT NOT NULL,
    tourist_id BIGINT NOT NULL,
    CONSTRAINT pk_trip_tourists PRIMARY KEY (trip_id, tourist_id),
    CONSTRAINT fk_trip_tourists_on_trip FOREIGN KEY (trip_id) REFERENCES trips(id),
    CONSTRAINT fk_trip_tourists_on_tourist FOREIGN KEY (tourist_id) REFERENCES tourists(id)
);
