CREATE TABLE travel_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    trip_id BIGINT NOT NULL,
    value INTEGER NOT NULL,
    comment VARCHAR(255),
    CONSTRAINT pk_travel_expenses PRIMARY KEY (id),
    CONSTRAINT fk_travel_expenses_on_trip FOREIGN KEY (trip_id) REFERENCES trips(id)
);
